ci: warn is `lib` is not up-to-date

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -19,7 +19,11 @@ jobs:
         with:
           node-version: 18.x
           cache: "npm"
-      - run: npm ci
+      - name: dependencies
+        run: |
+          npm ci
+          echo 'ℹ️  If this step fails, run `$ npm install` and commit the changes.'
+          exit $(git diff | wc -l)
       - run: npm run build --if-present
       - run: npm run test --if-present
       - name: formatting
